language: go
go:
  - "1.12.x"
  - master
env:
  - GO111MODULE=on
install: true
script:
  - ./test.sh
matrix:
  fast_finish: true
  allow_failures:
  - go: master
after_success:
  - bash <(curl -s https://codecov.io/bash)
